### ISSUE TITLE
Network card is messed up

### ISSUE THREAD

**Issue by FadeMind** [roines45/glow#1]
Status
WIFI is OFF
Ethernet is  ON and active.
![20231004-1696409725](https://github.com/roines45/glow/assets/9846948/7c87ffca-bbcb-4318-818f-779d3d070765)

glow report
![20231004-1696409872](https://github.com/roines45/glow/assets/9846948/909b08e8-e5a7-4a10-b457-8a04e4933154)
![20231004-1696409853](https://github.com/roines45/glow/assets/9846948/faa44440-6c62-4c41-80dc-e5401d94dd0b)

**Comment by roines45** [comment]
> Status WIFI is OFF Ethernet is ON and active. ![20231004-1696409725](https://user-images.githubusercontent.com/9846948/272518936-7c87ffca-bbcb-4318-818f-779d3d070765.png)
> 
> glow report ![20231004-1696409872](https://user-images.githubusercontent.com/9846948/272520142-909b08e8-e5a7-4a10-b457-8a04e4933154.png) ![20231004-1696409853](https://user-images.githubusercontent.com/9846948/272520150-faa44440-6c62-4c41-80dc-e5401d94dd0b.png)


Hello!

Glow's network part does not provide instant updates. If you change the network connection while the program is open, naturally it is not updated.

Can you check?

**Comment by FadeMind** [comment]
@roines45 WIFI status should be offline BUT it is reported as Gigabit Ethernet connection speed and active. No matter restart app. Same results. 

![20231004-1696412417](https://github.com/roines45/glow/assets/9846948/d70fea8b-4ffe-463d-bee6-f4d4293155dd)

Your app does not care if Wifi is ON or OFF (soft mode). 
![20231004-1696412554](https://github.com/roines45/glow/assets/9846948/515b6ba8-79c5-44b9-a570-dd5d0500cff7)

**Comment by roines45** [comment]
@FadeMind hello again!

I've made some edits and version V1.89 is now available. I hope some issues have been fixed.

Kind regards.

**Comment by FadeMind** [comment]
@roines45 nothing change on my end with latest build.

**Comment by roines45** [comment]
> @roines45 nothing change on my end with latest build.

Interesting. I think it might be something specific to your system, because when I test it with different systems, there is no prob
