### ISSUE TITLE
Sistem tipi yanlış gözüküyor.

### ISSUE THREAD

**Issue by lwrlock** [roines45/glow#1]
![image](https://github.com/roines45/glow/assets/137615326/2ed58519-7d4b-4319-9f42-2630d46c3eba)
Masaüstü Bilgisayar olarak gözüküyor ama laptop kullanıyorum. Bu şekilde olmasımı lazım yoksa?

**Comment by roines45** [comment]
> ![image](https://user-images.githubusercontent.com/137615326/262009586-2ed58519-7d4b-4319-9f42-2630d46c3eba.png) Masaüstü Bilgisayar olarak gözüküyor ama laptop kullanıyorum. Bu şekilde olmasımı lazım yoksa?

Hi @lwrlock,

Hello, the System Type feature is a temporary feature. So it may be problematic. It is a feature that will be completely removed with version v1.78.

Best regards.
