### ISSUE TITLE
Glow doesn't work in Windows11 Home

### ISSUE THREAD

**Issue by Duzeper** [roines45/glow#6]
Is Glow supposed to work with Windows11 Home?
I have no problems with Windows10 Pro (v22H2) and Windows11Pro (v23H2), but on a laptop running Windows11 Home (v22H2), when I double click Glow_x64.exe, all I see is a very brief 'egg-timer' then nothing. Also when I try to launch Glow, nothing happens in 'Task Manager' if it is open at the the time so there is nothing running in the background. 
I should point out that I am not running the executable from within the zip file but have extracted everything and all 3 machines are using the same downloaded files so not a download issue.

Martin Dashper

**Comment by roines45** [comment]
> Is Glow supposed to work with Windows11 Home? I have no problems with Windows10 Pro (v22H2) and Windows11Pro (v23H2), but on a laptop running Windows11 Home (v22H2), when I double click Glow_x64.exe, all I see is a very brief 'egg-timer' then nothing. Also when I try to launch Glow, nothing happens in 'Task Manager' if it is open at the the time so there is nothing running in the background. I should point out that I am not running the executable from within the zip file but have extracted everything and all 3 machines are using the same downloaded files so not a download issue.
> 
> Martin Dashper

Hello,

There is no such error.

**Comment by Duzeper** [comment]
Then why does my laptop display this behaviour?
I have to say that I feel that simply dismissing my problem by, effectively telling me it is not happening, is incredibly disrespectful.
